name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
  # python
  - mpi4py=3.1.3
  - python=3.9
  - pandas
  - numpy=1.24
  - scipy=1.9.0

  # jupyter
  - ipywidgets=7.7
  - itkwidgets=0.32.6
  - jupyter=1.0
  - jupyter_contrib_nbextensions=0.7
  - jupyter_nbextensions_configurator=0.6
  - jupyterlab=3.6
  - notebook=6.4

  # coding stuff
  - git=2.39

  # computing stuff
  - fenics=2019.1.0
  - gmsh=4.11
  - meshio=5.3

  # plotting stuff
  - matplotlib=3.7
  - gnuplot=5.4

  # pip for additional packages
  - pip=23.1
  - pip:
    - dolfin_mech==2024.10.17